# Generated by Django 2.1 on 2018-09-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20180904_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='born',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='died',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.TextField(blank=True, help_text='Enter any noteworthy information', max_length=1000),
        ),
    ]
