# Generated by Django 2.1 on 2018-09-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20180911_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='genre',
        ),
        migrations.AddField(
            model_name='piece',
            name='genre',
            field=models.ManyToManyField(help_text='Select one or more genres', to='catalogue.Genre'),
        ),
    ]
