# Generated by Django 2.1 on 2018-09-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20180911_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.AlterField(
            model_name='piece',
            name='arranger',
            field=models.ManyToManyField(blank=True, help_text='Select one or more names', related_name='arranger', to='catalogue.Person'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.ManyToManyField(blank=True, help_text='Select one or more names', to='catalogue.Person'),
        ),
    ]
