# Generated by Django 2.1 on 2018-10-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20180911_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Select one or more genres', to='catalogue.Genre'),
        ),
    ]
